var beruf = [
  "Abt/Äbtissin",
  "Altenpfleger/in",
  "Apotheker/in",
  "Architekt/in",
  "Artist/in",
  "Arzt/Ärztin",
  "Astronaut/in",
  "Augenoptiker/in",
  "Autohändler/in",
  "Bäcker/in",
  "Bademeister/in",
  "Barkeeper/in",
  "Bauer/Farmer",
  "Berführer/in",
  "Bergführer/in",
  "Bergmann/frau",
  "Betonbauer/in",
  "Bibliothekar/in",
  "Bierbrauer/in",
  "Binnenschiffer/in",
  "Biologe/Biologin",
  "Bootsbauer/in",
  "Boxer/in",
  "Briefträger/in",
  "Buchhändler/in",
  "Bundeskanzler/in",
  "Call-Center-Agent",
  "Chemiker/in",
  "Chorsänger/in",
  "Comedy-Autor",
  "Creative Director",
  "Dachdecker/in",
  "Damenschneider/in",
  "Designer/in",
  "Dirigent/in",
  "Diskjockey",
  "Dolmetscher/in",
  "Drogist/in",
  "Eheberater/in",
  "Eisverkäufer/in",
  "Elektriker/in",
  "Elektroniker/in",
  "Energieberater/in",
  "Ergotherapeuth/in",
  "Ernährungsberater/in",
  "Erzieher/in",
  "Event-Manager/in",
  "Fahrlehrer",
  "Fahrradkurier/in",
  "Fahrradmonteur/in",
  "Feuerwehrmann",
  "Fischer/in",
  "Fleischer",
  "Fleischer/in",
  "Fliesenleger/in",
  "Florist/in",
  "Fluglotse/Fluglotsin",
  "Fotograf/in",
  "Friedhofsgärtner/in",
  "Friseur/in",
  "Fussball-Schiedsrichter/in",
  "Gärtner/in",
  "Gebäudereiniger/in",
  "Geburtshelfer/in",
  "Gefängniswärter/in",
  "Geigenbauer/in",
  "Glaser/in",
  "Gleisbauer/in",
  "Goldschmied/in",
  "Großhandelskaufmann",
  "Gymnasiallehrer",
  "Hausfrau/Hausmann",
  "Headhunter",
  "Hörakustiker/in",
  "Hotelier",
  "Human Resources Manager/in",
  "Hundetrainer/in",
  "Imker/in",
  "Immobilienmakler/in",
  "Industriekletterer",
  "Informatiker/in",
  "Ingenieur",
  "Innenarchitekt/in",
  "Jäger",
  "Jazz-Musiker",
  "Journalist/in",
  "Jurist/in",
  "Kameramann/frau",
  "Kanalarbeiter/in",
  "Kapitän/in",
  "Klavierbauer/in",
  "Klempner/in",
  "Koch/Köchin",
  "Komponist/in",
  "Kosmetiker/in",
  "Krankenschwester/Krankenpfleger",
  "Kriminalkommissar/in",
  "Kulturstaatsminister/in",
  "Landwir/in",
  "Landwirt/in",
  "Logopäde/Logopädin",
  "Lokomotivführer/in",
  "Maler/in",
  "Marktforscher/in",
  "Maschinenbauer/in",
  "Masseur/in",
  "Maurer/in",
  "Mechatroniker/in",
  "Meteorologe/Meteorologin",
  "Möbelpacker/packerin",
  "Model",
  "Molkereiarbeiter",
  "Musiklehrer",
  "Ozeanograph",
  "Partyserviceunternehmer",
  "Pathologe",
  "Pfarrer",
  "Pförtner/in",
  "Physiker/in",
  "Pilot/in",
  "Polizist/in",
  "Programmierer/in",
  "Puppenspieler/in",
  "Raumausstatter/in",
  "Rechtsanwalt",
  "Rechtsanwalt/in",
  "Redenschreiber/in",
  "Regisseur/in",
  "Reiseleiter/in",
  "Rettungsschwimmer/in",
  "Richter/in",
  "Sanitäter/in",
  "Schädlingsbekämpfer/in",
  "Schäfer/in",
  "Schauspieler/in",
  "Schiffbauer/in",
  "Schornsteinfeger/in",
  "Schreiner/in",
  "Schuhmacher/in",
  "Sekretär/in",
  "Soldat/in",
  "Souffleur",
  "Spargelstecher",
  "Spargelstecher/in",
  "Sportlehrer/in",
  "Steinmetz/in",
  "Steuerfachangestellter/e",
  "Stuntman",
  "Stuntman/frau",
  "Surflehrer/in",
  "Tankwart",
  "Taxifahrer/in",
  "Tierarzt",
  "Tierpfleger",
  "Tischler",
  "Tischler/in",
  "Türsteher",
  "Türsteher/in",
  "Uhrmeister",
  "Uhrmeister/in",
  "Umweltschützer/in",
  "Unternehmensberater/in",
  "Veranstaltungskaufmann/frau",
  "Verkäufer/in",
  "Versteiger",
  "Versteigerer/in",
  "Verteidigungsminister",
  "Verteidigungsminister/in",
  "Waffenhändler/in",
  "Wahlforscher",
  "Wahlforscher/in",
  "Wasserbauer/in",
  "Weihnachtsmann",
  "Winzer",
  "Winzer/in",
  "Zahnarzt",
  "Zahnarzt/in",
  "Zeitungszusteller",
  "Zeitungszusteller/in",
  "Zerspanungsmechaniker/in",
  "Zimmerer",
  "Zimmerer/in",
  "Zoohändler/in",
  "Zugbegleiter",
  "Zugbegleiter/in"
];

var hobby = [
  "Angeln",
  "Büchernarr",
  "Hobbykoch",
  "Pflanzen züchten (Pilze, Kakteen ...)",
  "Philosoph / Meditieren",
  "Sammler (Briefmarken, Teddybären, Münzen ...)",
  "Sport (Fussball, Autorennen, Snowboard, Skateboard, Paragleiding ...)",
  "Tiere züchten (Spinnen, Regenwürmer ...)",
  "Wandern (Wandern, Bergsteigen ...)",
  "Wassersport (Segeln, Wasserskifahren, Kajak, Kanu, Kitesurfen, Surfen, Schwimmen, Turmspringen, Synchronschwimmen, Wasserball, Wildwasser, Tauchen)",
  "Darstellung des Mittelalters, der römischen Geschichte...",
  "Musizieren (Klavier, Flöte, Cello, Gitarre, Kofferradio)",
  "Fotografieren",
  "Malen und Zeichnen (Aktzeichnen, Landschaftsbilder, Ölbilder, Kohlezeichnung)",
  "Kleingarten (Rasen mähen, Säen, Ernten, Pflücken, Baumschneiden, Umgraben, Giessen",
  "Tanzen (Standardtanzen, Latein, Salsa, Ballett, Hip Hop, Breakdance, Jazztanz, Formationstanz)",
  "Wintersport (Skifahren, Eiskunstlaufen, Bobfahren, Skispringen, Curling)",
  "Kneipensport (Billard, Pool, Dart, Tischfussball",
  "Kegeln, Bowling"
];

var tick = [
  "Kratzt sich ständig am Kopf",
  "Ständiges Nasejucken",
  "Zucken der Mundwinkel",
  "Rucken des Kopfes",
  "Reiben im Schritt",
  "Hochziehen der Augenbrauen",
  "Zwinkern mit einem Auge",
  "Ständiges Räuspern",
  "Schuhtick",
  "Kleptomanie (Zwang etwas stehlen zu müssen)",
  "Waschzwang",
  "Pyromanie (Zwang, ein Feuer zu legen)"
];

var gefuehl = [
  "abgespannt",
  "ablehnend",
  "achtsam",
  "aggressiv",
  "akzeptierend",
  "alarmiert",
  "albern",
  "ambivalent",
  "angeekelt",
  "angeregt",
  "angespannt",
  "angewidert",
  "ängstlich",
  "angstschlotternd",
  "antriebslos",
  "ärgerlich",
  "argwöhnisch",
  "arrogant",
  "aufgebracht",
  "aufgedreht",
  "aufgeregt",
  "aufgewühlt",
  "ausgeglichen",
  "ausgelassen",
  "ausgelaugt",
  "beängstigt",
  "bedrängt",
  "bedrückt",
  "beeindruckt",
  "befangen",
  "beflügelt",
  "befreit",
  "befriedigt",
  "begeistert",
  "begierig",
  "behaglich",
  "beklommen",
  "bekümmert",
  "belastet",
  "belebt",
  "beleidigt",
  "belustigt",
  "berauscht",
  "bereit",
  "bereuend",
  "beruhigt",
  "berührt",
  "beschämt",
  "beschwingt",
  "beseelt",
  "besorgt",
  "bestürzt",
  "betroffen",
  "betrübt",
  "beunruhigt",
  "bewegt",
  "bewundernd",
  "bezaubert",
  "bitter",
  "blockiert",
  "brummig",
  "dankbar",
  "depressiv",
  "deprimiert",
  "distanziert",
  "dumpf",
  "durcheinander",
  "ehrfürchtig",
  "eifersüchtig",
  "eifrig",
  "einsam",
  "ekelerfüllt",
  "empfindlich",
  "empört",
  "energiegeladen",
  "energisch",
  "engagiert",
  "enthusiastisch",
  "entlastet",
  "entmutigt",
  "entrüstet",
  "entschieden",
  "entschlossen",
  "entsetzt",
  "entspannt",
  "enttäuscht",
  "entzückt",
  "erfreut",
  "erfrischt",
  "erfüllt",
  "ergriffen",
  "erheitert",
  "erleichtert",
  "erleuchtet",
  "ermüdet",
  "ermuntert",
  "ermutigt",
  "ernüchtert",
  "erregt",
  "erschlagen",
  "erschöpft",
  "erschrocken",
  "erstaunt",
  "erwartungsvoll",
  "fasziniert",
  "feindselig",
  "feinsinnig",
  "frei",
  "freuen",
  "friedlich",
  "froh",
  "fröhlich",
  "frustriert",
  "fügsam",
  "furchtsam",
  "fürsorglich",
  "gebannt",
  "geborgen",
  "geduldig",
  "gefasst",
  "gefesselt",
  "gehässig",
  "gehemmt",
  "geladen",
  "gelangweilt",
  "gelassen",
  "gelöst",
  "gemütlich",
  "gequält",
  "gereizt",
  "gerührt",
  "gerzeizt",
  "geschützt",
  "gespannt",
  "gestört",
  "gleichgültig",
  "glücklich",
  "glückselig",
  "gütig",
  "hassend",
  "hasserfüllt",
  "heiter",
  "hellwach",
  "herzlich",
  "hilflos",
  "hingerissen",
  "hocherfreut",
  "hoffnungsvoll",
  "inspiriert",
  "intellektuell",
  "interessiert",
  "irritiert",
  "jämmerlich",
  "kalt",
  "klar",
  "kraftvoll",
  "kribbelig",
  "lebendig",
  "lebhaft",
  "leer",
  "leicht",
  "liebevoll",
  "locker",
  "lüstern",
  "lustig",
  "lustlos",
  "lustvoll",
  "melancholisch",
  "missmutig",
  "misstrauisch",
  "motiviert",
  "müde",
  "munter",
  "mürrisch",
  "mutig",
  "mutlos",
  "nachdenklich",
  "neidisch",
  "nervös",
  "neugierig",
  "niedergeschlagen",
  "offen",
  "ohnmächtig",
  "optimistisch",
  "panisch",
  "pedantisch",
  "peinlich",
  "perplex",
  "pessimistisch",
  "ratlos",
  "respektvoll",
  "ruhelos",
  "ruhig",
  "satt",
  "sauer",
  "scheu",
  "schläfrig",
  "schlapp",
  "schockiert",
  "schwermütig",
  "schwunglos",
  "schwungvoll",
  "selbstsicher",
  "selig",
  "sensibel",
  "sicher",
  "skeptisch",
  "sorgenfrei",
  "sorgenvoll",
  "sorglos",
  "still",
  "stolz",
  "strapaziert",
  "streitlustig",
  "stressfrei",
  "tapfer",
  "tatkräftig",
  "teilnahmslos",
  "tollkühn",
  "träge",
  "traurig",
  "überdrüssig",
  "überfordert",
  "überglücklich",
  "überlastet",
  "übermütig",
  "überrascht",
  "überschäumend",
  "überschwänglich",
  "überwältigt",
  "überzeugt",
  "unbehaglich",
  "unbekümmert",
  "unbeschwert",
  "unbeteiligt",
  "unerschütterlich",
  "ungeduldig",
  "ungehalten",
  "ungemütlich",
  "unglücklich",
  "unklar",
  "unnahbar",
  "unruhig",
  "unschlüssig",
  "unsicher",
  "unter Druck",
  "unwohl",
  "unzufrieden",
  "verängstigt",
  "verärgert",
  "verbittert",
  "verblüfft",
  "vergnügt",
  "verlegen",
  "verletzbar",
  "verletzt",
  "verliebt",
  "verloren",
  "verrückt",
  "verschlafen",
  "verschlossen",
  "verschreckt",
  "verspannt",
  "verspielt",
  "verstimmt",
  "verstört",
  "vertrauend",
  "vertrauensvoll",
  "verunsichert",
  "verwirrt",
  "verwundert",
  "verzagt",
  "verzaubert",
  "verzückt",
  "verzweifelt",
  "voller Vorfreude",
  "vorwurfsvoll",
  "wach",
  "warmherzig",
  "weinerlich",
  "widerwillig",
  "wissbegierig",
  "wohl",
  "wolllüstig",
  "wütend",
  "zappelig",
  "zärtlich",
  "zerknirscht",
  "zermürbt",
  "zerrissen",
  "zittrig",
  "zögerlich",
  "zornig",
  "zufrieden",
  "zugeneigt",
  "zugewandt",
  "zutraulich",
  "zuversichtlich",
  "zweifelnd",
  "zynisch"
];

var gefuehlAngenehm = [
  "achtsam",
  "akzeptierend",
  "angeregt",
  "aufgedreht",
  "aufgeregt",
  "ausgeglichen",
  "ausgelassen",
  "beeindruckt",
  "beflügelt",
  "befreit",
  "befriedigt",
  "begeistert",
  "begierig",
  "behaglich",
  "belebt",
  "belustigt",
  "berauscht",
  "bereit",
  "beruhigt",
  "berührt",
  "beschwingt",
  "beseelt",
  "bewegt",
  "bewundernd",
  "bezaubert",
  "dankbar",
  "eifrig",
  "energiegeladen",
  "energisch",
  "engagiert",
  "enthusiastisch",
  "entlastet",
  "entschlossen",
  "entspannt",
  "entzückt",
  "erfreut",
  "erfrischt",
  "erfüllt",
  "ergriffen",
  "erheitert",
  "erleichtert",
  "erleuchtet",
  "ermuntert",
  "ermutigt",
  "erregt",
  "erstaunt",
  "erwartungsvoll",
  "fasziniert",
  "feinsinnig",
  "frei",
  "freuen",
  "friedlich",
  "froh",
  "fröhlich",
  "gebannt",
  "geborgen",
  "geduldig",
  "gefasst",
  "gefesselt",
  "gelassen",
  "gemütlich",
  "gerührt",
  "geschützt",
  "gespannt",
  "glücklich",
  "glückselig",
  "gütig",
  "heiter",
  "hellwach",
  "herzlich",
  "hingerissen",
  "hocherfreut",
  "hoffnungsvoll",
  "inspiriert",
  "interessiert",
  "klar",
  "kraftvoll",
  "lebendig",
  "lebhaft",
  "leicht",
  "liebevoll",
  "locker",
  "lustig",
  "lustvoll",
  "motiviert",
  "munter",
  "mutig",
  "neugierig",
  "offen",
  "optimistisch",
  "respektvoll",
  "ruhig",
  "satt",
  "schwungvoll",
  "selbstsicher",
  "selig",
  "sensibel",
  "sicher",
  "sorgenfrei",
  "sorglos",
  "still",
  "stolz",
  "stressfrei",
  "tapfer",
  "tatkräftig",
  "überglücklich",
  "übermütig",
  "überrascht",
  "überschäumend",
  "überschwänglich",
  "überwältigt",
  "unbekümmert",
  "unbeschwert",
  "unerschütterlich",
  "verblüfft",
  "vergnügt",
  "verliebt",
  "verspielt",
  "vertrauend",
  "vertrauensvoll",
  "verwundert",
  "verzaubert",
  "verzückt",
  "voller Vorfreude",
  "wach",
  "warmherzig",
  "wissbegierig",
  "wohl",
  "zärtlich",
  "zufrieden",
  "zugeneigt",
  "zugewandt",
  "zutraulich",
  "zuversichtlich"
];

var koerperteil = [
  "Achsel",
  "Arm",
  "Auge",
  "Augenlid",
  "Backe/Wange",
  "Bauch",
  "Bein",
  "Brust",
  "Busen",
  "Daumen",
  "Ellbogen/Ellenbogen",
  "Ferse",
  "Finger",
  "Fuss",
  "Gaumen",
  "Gesäss",
  "Hals",
  "Hand",
  "Haupt",
  "Hüfte",
  "Kinn",
  "Knie",
  "Kopf",
  "Leber",
  "Lippe",
  "Luftröhre",
  "Lunge",
  "Mund",
  "Nase",
  "Niere",
  "Oberarm",
  "Oberschenkel",
  "Ohr",
  "Rücken",
  "Schulter",
  "Stirn",
  "Unterarm",
  "Unterschenkel",
  "Wade",
  "Zahn",
  "Zehe",
  "Zunge"
];

var tier = [
  "Aal",
  "Adler",
  "Affe",
  "Afrikanischer Wildhund",
  "Albatros",
  "Alligator",
  "Ameise",
  "Ameisenbär",
  "Bär",
  "Beo",
  "Biber",
  "Biene",
  "Bison",
  "Blutegel",
  "Boa",
  "Braunbär",
  "Chamäleon",
  "Clownfisch",
  "Dachs",
  "Delfin",
  "Dinosaurier",
  "Dodo",
  "Echse",
  "Eichhörnchen",
  "Eidechse",
  "Eisbär",
  "Elche",
  "Elefant",
  "Ente",
  "Erdferkel",
  "Erdmännchen",
  "Esel",
  "Eule",
  "Faultier",
  "Feldhase",
  "Feldmaus",
  "Fisch",
  "Flamingo",
  "Fledermaus",
  "Fliege",
  "Fliegender Fisch",
  "Flughund",
  "Flusspferd",
  "Frettchen",
  "Frosch",
  "Fuchs",
  "Gans",
  "Gazelle",
  "Geier",
  "Gepart",
  "Giraffe",
  "Goldfisch",
  "Gorilla",
  "Gottesanbeterin",
  "Grashüpfer",
  "Graupapagei",
  "Gürteltier",
  "Hahn",
  "Hai",
  "Hamster",
  "Hase",
  "Hausmaus",
  "Hausrind",
  "Hermelin",
  "Hirsch",
  "Hornisse",
  "Huhn",
  "Hummer",
  "Hund",
  "Husky",
  "Hyäne",
  "Igel",
  "Igelfisch",
  "Japanische Riesenkrabbe",
  "Käfer",
  "Kamel",
  "Känguru",
  "Kaninchen",
  "Karpfen",
  "Katze",
  "Koala",
  "Kojote",
  "Kondor",
  "Krähe",
  "Krake",
  "Kranich",
  "Krebs",
  "Krokodil",
  "Kröte",
  "Küchenschabe",
  "Kuh",
  "Lachener Hans",
  "Lama",
  "Laubfrosch",
  "Laus",
  "Leguan",
  "Lemming",
  "Leopard",
  "Löwe",
  "Luchs",
  "Mammut",
  "Marienkäfer",
  "Maultier",
  "Maulwurf",
  "Maus",
  "Meerschwein",
  "Meise",
  "Merinoschaf",
  "Milan",
  "Milbe",
  "Molch",
  "Mungo",
  "Murmeltier",
  "Nacktmull",
  "Nashorn",
  "Nilpferd",
  "Oktopusse",
  "Opossum",
  "Orang-Utan",
  "Otter",
  "Panda",
  "Panther",
  "Papagei",
  "Pavian",
  "Pelikan",
  "Pfau",
  "Pferd",
  "Pinguin",
  "Piranha",
  "Präriehund",
  "Qualle",
  "Rabe",
  "Ratte",
  "Raupe",
  "Regenwurm",
  "Reh",
  "Reiher",
  "Rentier",
  "Robbe",
  "Roche",
  "Säbelzahntiger",
  "Salamander",
  "Schabe",
  "Schaf",
  "Schakale",
  "Schildkröte",
  "Schimpanse",
  "Schlange",
  "Schmetterling",
  "Schnabelbarsch",
  "Schnabeltier",
  "Schnecke",
  "Schneeeule",
  "Schwamm",
  "Schwan",
  "Schwein",
  "Schwertwal/Orca",
  "Seehund",
  "Seelöwe",
  "Seepferdchen",
  "Seestern",
  "Seeteufel",
  "Sibirischer Tiger",
  "Siebenschläfer",
  "Skorpion",
  "Spatz",
  "Specht",
  "Spinne",
  "Sri-Lanka-Elefant",
  "Stachelschwein",
  "Steinbock",
  "Stier",
  "Stinktier",
  "Storch",
  "Strauss",
  "Streifenhörnchen",
  "Tapir",
  "Taube",
  "Tausendfüssler",
  "Termiten",
  "Tiger",
  "Tintenfisch",
  "Totenkopfäffchen",
  "Uhu",
  "Vogel",
  "Vogelspinne",
  "Wal",
  "Walross",
  "Wanzen",
  "Warane",
  "Warzenschwein",
  "Waschbär",
  "Weinbergschnecke",
  "Weissstorch",
  "Wellensittich",
  "Widder",
  "Wiesel",
  "Wildschwein",
  "Wolf",
  "Wurm",
  "Wüstenmaus",
  "Wüstenrennmaus",
  "Zebra",
  "Zecke",
  "Ziege",
  "Zitteraal"
];

var fabelwesen = [
  "Bigfoot",
  "Dämon",
  "Drache",
  "Eierlegende Wollmilchsau",
  "Einhorn",
  "Elfe",
  "Fee",
  "Flaschengeist",
  "Gespenst",
  "Gnom",
  "Godzilla",
  "Heinzelmännchen",
  "Hexe",
  "Kobold",
  "Meerjungfrau",
  "Mumie",
  "Ork",
  "Osterhase",
  "Pegasus",
  "Phönix",
  "Poltergeist",
  "Riese",
  "Sandmann",
  "Schlumpf",
  "Sphinx",
  "Sirene",
  "Titan",
  "Troll",
  "Vampir",
  "Weihnachtsmann",
  "Werwolf",
  "Yeti",
  "Zahnfee",
  "Zauberer",
  "Zombie",
  "Zwerg"
];

var phobie = [
  "Aviophopie (Flugangst)",
  "Anuptaphobie (Angst alleinstehend zu bleiben)",
  "Klaustrophobie (Angst vor engen Räumen)",
  "Agoraphobie (Angst vor freien grossen Plätzen)",
  "Arachnophobie (Angst vor Spinnen)",
  "Herpetophobie (Angst vor Kriechtieren)",
  "Hippopotomonstrosesquippedaliophobie (Angst vor langen Wörtern ;-) (eigentlich: Sesquipedalophobie)",
  "Caligynephobie (Angst vor schönen Frauen)",
  "Genophobie (Angst vor Liebe/Nähe)",
  "Dentophobie (Angst vor dem Zahnarzt)",
  "Chaetophobie (Angst vor Haaren)",
  "Mysophobie (Angst vor Unsauberkeit/Bakterien/Krankheiten)",
  "Gephyrophobie (Brücken zu überqueren)",
  "Erythrophobie (Angst vor dem Erröten)",
  "Dysmorphophobie (Angst vor der Hässlichkeit des eigenen Gesichts oder Körpers)",
  "Akrophobie (Höhenangst oder Höhenschwindel)",
  "Keraunophobie (Angst vor Donner)",
  "Elektrophobie (Angst vor Elektrogeräten)",
  "Nyktophobie (Angst vor der Dunkelheit oder Nacht)",
  "Astraphobie (Angst vor Blitzen)",
  "Phobophobie (Angst eine Phobie zu erleiden)"
];

var ort = [
  "Messestand",
  "Muckibude/Fitnessstudio",
  "Nagelstudio",
  "Schlachterei",
  "Schule",
  "Sonnenstudio",
  "Steuerberaterkanzlei",
  "Supermarkt",
  "Waschsalon",
  "Werbeagentur",
  "Würstchenbude",
  "Zahnarzt",
  "Zoofachgeschäft",
  "Zweithaarstudio",
  "Argentinien",
  "Australien",
  "Belgien",
  "Deutschland",
  "Frankreich",
  "Italien",
  "Japan",
  "Mexico",
  "Niederlande",
  "Österreich",
  "Russland",
  "Schweiz",
  "Spanien",
  "USA",
  "Berg, Berggipfel",
  "Gebirge",
  "Gletscher",
  "Wald",
  "See (Stausee, Baggersee)",
  "Steppe",
  "Strand",
  "Sumpf",
  "Wiese",
  "Wüste",
  "Höhle",
  "Park",
  "im/am Fluss",
  "unter Wasser (Meer, Fluss), Tiefsee",
  "Regenwald",
  "Dschungel",
  "Hochgebirge",
  "Oase",
  "Bergwiese",
  "Watt",
  "einsame Insel",
  "Moor",
  "Savanne",
  "Wasserfall",
  "im Irrgarten",
  "Bibliothek",
  "Einwohnermeldeamt",
  "Kino",
  "Konzertsaal",
  "Theater",
  "Praxis",
  "Standesamt",
  "KFZ-Zulassungsstelle",
  "Museum",
  "Arbeitszimmer",
  "Badezimmer",
  "Besenkammer",
  "Hobbyraum",
  "Kinderzimmer",
  "Schlafzimmer",
  "Wohnzimmer",
  "Küche",
  "Garage",
  "begehbarer Schrank",
  "Abstellraum",
  "Musikzimmer",
  "Gästezimmer",
  "Speisekammer",
  "Keller",
  "Dachboden",
  "Ankleidezimmer",
  "Kaminzimmer",
  "Balkon",
  "Gartenhaus",
  "WG Küche",
  "Speisezimmer",
  "Haushaltsraum",
  "Mond, Planeten",
  "Himmel",
  "Hölle",
  "Paradies",
  "Raumschiff",
  "Raumstation",
  "Spukschloss",
  "im menschlichem Körper",
  "fliegender Teppich",
  "Zeitmaschine",
  "Mikrokosmos",
  "Olymp",
  "Atom(modell) und Molekül(modell)",
  "Saloon",
  "Gesindezimmer",
  "Höhle von Urmenschen",
  "römischer/griechischer ... Marktplatz",
  "Ritterburg",
  "Atlantis",
  "Limes",
  "Turm von Babel",
  "Folterkammer",
  "Pyramide (z.B. in Grabkammer)",
  "vor dem Stadttor",
  "Schützengraben",
  "Trümmergrundstück",
  "Schlachtfeld",
  "Bunker",
  "im Sarkophag",
  "Schiff/U-Boot (drauf oder drinnen)",
  "Kreuzfahrtschiff",
  "Fischkutter",
  "Flugzeug",
  "Auto, LKW, Bus",
  "Wohnwagen, Wohnmobil",
  "Motorrad",
  "Zug",
  "Seilbahn",
  "Kutsche",
  "Fahrstuhl",
  "Zeppelin",
  "Ballonkorb",
  "Strassenbahn",
  "Bus",
  "auf der Kanonenkugel",
  "auf dem Pferd",
  "unter der Brücke",
  "auf der Brücke",
  "Krematorium",
  "Friedhof",
  "Kirmes-/Jahrmarktsgerät (z.B. Riesenrad, Geisterbahn)",
  "Telefonzelle",
  "Weihnachtsmarkt",
  "Verkehrsübungsplatz",
  "Baumschule",
  "im gegnerischen Strafraum",
  "Sanatorium",
  "Zoo",
  "Zirkus",
  "auf dem Jakobsweg",
  "auf dem Laufsteg",
  "Orchestergraben",
  "Zu-Spät-Kommer-Loge im Theater"
];

var gebaeude = [
  "Aussichtsturm",
  "Bauernhaus",
  "Geschäft",
  "Hochhaus",
  "Hühnerstall",
  "Kaserne",
  "Kirche/Kapelle/Kathedrale",
  "Kloster",
  "Krankenhaus (OP, Kreissaal, Notaufnahme, Säuglingstation, Röntgenraum, Gipsraum)",
  "Polizeistation (Ausnüchterungszelle)",
  "Rathaus",
  "Wolkenkratzer",
  "Stadion",
  "Pyramide",
  "Gefängnis",
  "Eisstation",
  "Eiffelturm",
  "Forsthaus",
  "Anwaltskanzlei",
  "Baumarkt",
  "Betriebsversammlung",
  "Bordell",
  "Büro",
  "Chefsekretariat",
  "Fabrik (Fliessband)",
  "Friseur",
  "Grossraumbüro",
  "Hafen",
  "Internetcafe",
  "Kantine",
  "Kieferorthopäde",
  "Kindergarten",
  "Markthalle",
  "Marktplatz",
  "Massagepraxis",
  "Messestand",
  "Muckibude/Fitnessstudio",
  "Nagelstudio",
  "Schlachterei",
  "Schule",
  "Sonnenstudio",
  "Steuerberaterkanzlei",
  "Supermarkt",
  "Waschsalon",
  "Werbeagentur",
  "Würstchenbude",
  "Zahnarzt",
  "Zoofachgeschäft",
  "Zweithaarstudio"
];

var land = [
  "Argentinien",
  "Australien",
  "Belgien",
  "Deutschland",
  "Frankreich",
  "Italien",
  "Japan",
  "Mexico",
  "Niederlande",
  "Österreich",
  "Russland",
  "Schweiz",
  "Spanien",
  "USA"
];

var raum = [
  "Bibliothek",
  "Einwohnermeldeamt",
  "Kino",
  "Konzertsaal",
  "Theater",
  "Praxis",
  "Standesamt",
  "KFZ-Zulassungsstelle",
  "Museum",
  "Arbeitszimmer",
  "Badezimmer",
  "Besenkammer",
  "Hobbyraum",
  "Kinderzimmer",
  "Schlafzimmer",
  "Wohnzimmer",
  "Küche",
  "Garage",
  "begehbarer Schrank",
  "Abstellraum",
  "Musikzimmer",
  "Gästezimmer",
  "Speisekammer",
  "Keller",
  "Dachboden",
  "Ankleidezimmer",
  "Kaminzimmer",
  "Balkon",
  "Gartenhaus",
  "WG Küche",
  "Speisezimmer",
  "Haushaltsraum"
];

var fortbewegungsmittel = [
  "Schiff/U-Boot (drauf oder drinnen)",
  "Kreuzfahrtschiff",
  "Fischkutter",
  "Flugzeug",
  "Auto, LKW, Bus",
  "Wohnwagen, Wohnmobil",
  "Motorrad",
  "Zug",
  "Seilbahn",
  "Kutsche",
  "Fahrstuhl",
  "Zeppelin",
  "Ballonkorb",
  "Strassenbahn",
  "Bus",
  "auf der Kanonenkugel",
  "auf dem Pferd"
];

var routine = [
  "Tapezieren",
  "Streichen (Wände, Fenster)",
  "Bügeln",
  "Wäsche aufhängen",
  "Bier zapfen, Flaschen öffnen uä. Thekentätigkeiten",
  "Meditieren (im Schneidersitz sitzen)",
  "Fernsehen (sitzend auf einen Punkt starren, mit Hilfe der Fernbedienung zappen)",
  "Kochen (Zutaten hinzufügen, Hitze einstellen, Umrühren, Würzen usw.)",
  "Töpfern und etwas Rundes formen an einer drehenden Töpferscheibe",
  "am Computer (-bildschirm) arbeiten und Tastatur bedienen",
  "aktiv am Fitnessgerät sein",
  "Boden wischen oder fegen",
  "Fenster putzen",
  "Fegen",
  "Beten (Kirche)",
  "Holz hacken",
  "Sägen",
  "Auto fahren (Lenken, Schalten)",
  "Gartenarbeit (Unkraut zupfen, Einpflanzen, Ernten, Rasen mähen)",
  "Blumen giessen",
  "Schwimmen",
  "Leiter hochsteigen",
  "Musizieren, z.B. Klavier, Gitarre, Geige spielen",
  "Ein Bild malen oder jemanden porträtieren",
  "Sport treiben, z.B. Dart, (Tisch-)Tennis, (Mini-)Golf",
  "Duschen oder Baden",
  "Nähen, Stricken, Häkeln",
  "Händewaschen",
  "Zähne putzen",
  "Nägel schneiden oder Lackieren",
  "Zigarette anzünden und rauchen",
  "Getränk einschenken und trinken",
  "Geschirr spülen",
  "sich sonnen (mit Handtuch ausbreiten, Eincremen)",
  "am Fliessband arbeiten",
  "handwerklich arbeiten (z.B. Schuh besohlen)"
];

var genreFernseh = [
  "Abenteuerfilm",
  "Actionfilm",
  "Adelsromanze",
  "Amateurfilm",
  "Bergfilm / Bergsteigerdrama",
  "Bibelfilm / Sandalenfilm",
  "Bollywood Film / Indische Liebesfilme",
  "Dogma (mit verwackelter Handkamera",
  "Eastern / Kung Fu",
  "Erotikfilm",
  "Fantasy",
  "Fassbinder-Filme",
  "Film Noir / Fanzösischer Film der 50er Jahre",
  "Heimatfilm",
  "Historienfilm",
  "Horrorfilm / Zombiefilm / Kettensägemassaker",
  "Horrorkomödie",
  "Katastrophenfilm / Flugzeugkatastrophe / Weltuntergangs Szenario",
  "Kinderfilm",
  "Komödie",
  "Kriegsfilm",
  "Kriminalfilm",
  "Liebesfilm",
  "Mantel und Degen / Drei Musketiere",
  "Märchen",
  "Martial Art",
  "Melodram",
  "Milieustudie",
  "Monumentalfilm",
  "Monsterfilm / Gozilla / King Kong",
  "Musik-Film",
  "Piratenfilm",
  "Porno (Softcore/Hardcore)",
  "Roadmovie",
  "Sandalenepos",
  "Science Fiction, Weltraumepos, Begegnung mit Ausserirdischen",
  "Spionage: James Bond 007; Der Spion der aus der Kälte kam, …",
  "Sex - Komödie",
  "Slapstick",
  "Splatter",
  "Spionagefilm",
  "Stummfilm",
  "Superhelden - Supermann, Batman und andere Comicvorlagen",
  "Teenager - Komödie",
  "Thriller",
  "Tragödie",
  "Tragikomödie",
  "Vampirfilm",
  "Western: Western, Italowestern (Spaghetti-Western), Western Komödie",
  "Zeichentrick /Comic / Manga",
  "Arztserie",
  "Beratungssendung: Medizinische Themen",
  "Dokusoap: Auswanderer, Kindererziehung, Haus einrichten",
  "Gerichtssendung",
  "Gottesdienst, Fernsehprediger",
  "Grand Prix d'Eurovision",
  "Hitparade",
  "Infotainment",
  "Kindersendung (Sesamstrasse, Sendung mit der Maus)",
  "Kochshow",
  "Komödienstadl",
  "Kultursendung / Arte",
  "Kunst und Krempel (Antiquitäten Experten beraten)",
  "Musikantenstadl",
  "Nachrichtensendung (Tagesschau)",
  "Reality-TV",
  "Reise- / Städtemagazin",
  "Reportage",
  "Sitcom",
  "Soap, Seifenoper",
  "Sport: Sportschau, Live-Übertragung",
  "Sprachkurs",
  "Genre Talkshow",
  "Telekolleg",
  "Genre Teleshop (Dauerwerbesendung)",
  "Tierdoku",
  "Verkehrserziehungsspots: Der 7. Sinn",
  "Wahlstudio",
  "Wahlwerbung",
  "Werbung und Mainzelmännchen",
  "Wetterbericht",
  "Wiso / Politik und Wirtschaft",
  "Wissenschaft",
  "Wissenschaftsshow",
  "Wort am Sonntag",
  "XY Ungelöst"
];

var genreMusik = [
  "Gregorianische Gesänge",
  "Mittelalterliche Musik",
  "Kirchenmusik / Orgel und Coral",
  "Moritatensänger / Minnesänger",
  "Sauf- / Studentenlied",
  "Liebeslied / derbe Lieder",
  "Stummfilm / Ragtime",
  "Oper (siehe Theater)",
  "Kunstlied / Sänger und Klavier (Schubert)",
  "12 Ton Musik / atonale Musik (einfach schräg singen!)",
  "Minimal Musik",
  "Ambient (Viel Musik wenig Gesang)",
  "Italienisches Bell Canto (Pavarotti)",
  "chinesische Oper/Musik",
  "Operette",
  "Musical",
  "Jazz / Jazzbalade / Jazzsong (Standard)",
  "Dixieland / Louis Amstrong",
  "Latin Jazz / Bossa Nova",
  "Elektrik Jazz / Rock Jazz",
  "Free Jazz / Archi Shepp",
  "Punk Jazz / sehr heftiges Schlagzeug, Gesang wie bei Punk",
  "Salsa / Merenge",
  "Afrikanischer Pop / M. Makeba",
  "Reggae",
  "Country & Western",
  "Hilly Billy",
  "Motown",
  "Soul",
  "Genre Gospel",
  "Singer & Songwriter",
  "Liedermacher",
  "Chanson / Canzoni",
  "Volksmusik (auch außereuropäisch)",
  "Irish Folk",
  "Bauchtanzmusik",
  "klassische chinesische Musik",
  "Indianertanz / Schamananentanz",
  "Afrikanische Musik (Trommeln, Vorsänger und Kehrreim)",
  "Obertongesang",
  "Jodeln",
  "Gstanzl (Bayerisches Couplé nur für Eingeweihte)",
  "Kabarett Lied",
  "Couplé / Spottlied",
  "Sozialistisches Arbeiterlied",
  "Volkstümliche Musik (Musikantenstadl)",
  "Genre Schlager",
  "Rock",
  "Hard Rock",
  "Death Metal",
  "Heavy Metal",
  "Punk",
  "Neue Deutsche Welle",
  "Techno / Elektronische Musik",
  "Rap",
  "Genre Hip Hop",
  "A Capella / A Capella Instrumental",
  "Kinderlied"
];

var beziehung = [
  "Ehepaar",
  "Vater/Kind",
  "Mutter/Kind",
  "Schwiegermutter und Schwiegertochter/Sohn o.ä.",
  "Geschwister",
  "Grosseltern und Enkel",
  "Stiefeltern/Stiefkind",
  "Patchwork-Familie",
  "Ehepaar",
  "Prostituierte und Freier",
  "Alternder Liebhaber",
  "Erwischter Geliebter",
  "Dreiecksverhältnis",
  "Erste Verabredung",
  "Schwules Pärchen",
  "Ex-Frau und neue Frau",
  "Ex-Mann und neuer Mann",
  "Lehrer und Schüler",
  "Lehrer und Schulleiter",
  "Lehrer und Eltern",
  "Schüler und Gang",
  "Verrückter Professor",
  "Ausbildungsoffizier und Rekrut",
  "Wächter und Gefangener",
  "Rechtsanwalt und Klient",
  "Richter und Rechtsanwalt",
  "Kriminalkommissar und Ganove/Verbrecher",
  "Autobahnpolizist und Autofahrer",
  "Sheriff und Gangsterbande",
  "Verkehrspolizist und Temposünder (auch Knöllchenverteiler und Falschparker)",
  "Terrorist und Geisel",
  "Angeklagter und Richter",
  "Psychopath und Opfer",
  "Film/Popstar und Fan",
  "Schauspieler und Regisseur",
  "Regisseur und Produzent",
  "Schauspieler und Stunt-Double",
  "Spermium und Eizelle",
  "X-Chromosom und Y-Chromosom",
  "Blutzelle und Bakterium",
  "PC und Benutzer",
  "Früchte in der Obstschale",
  "Roboter und sein Schöpfer",
  "Kind und Spielzeug/Puppe",
  "Bauchredner und Puppe",
  "Zahnstocher und Zahn/Gebiss",
  "5-Euro-Schein und 100-Euro-Schein",
  "Hund und Knochen",
  "Ratte und Laborwissenschaftler",
  "Fisch und der Wurm am Haken",
  "Frosch und Prinzessin",
  "Präparator und Tier",
  "Herrchen/Frauchen/Kind und Haustier",
  "(schlechtes) Gewissen und (zugehöriger) Mensch",
  "Gott und Mensch",
  "Gott und Teufel",
  "Buddha und Christus",
  "Dämon und Engel",
  "Alice und das weisse Kaninchen",
  "Astronaut und Ausserirdischer",
  "Seele und Person",
  "Erste Begegnung (Mensch und Ausserirdischer)",
  "'weisse Mäuse' und die Person, die halluziniert",
  "Mensch und Spiegelbild",
  "Person und eingebildeter Freund (z.B. Harvey)",
  "Kapitän und Geist",
  "romantischer Mann und die Blumen, die er mit sich trägt",
  "Totengräber und Geist/Leiche",
  "Cowboy und Indianer",
  "Räuber und Gendarm",
  "Batman und Robin",
  "Kasper und Seppel/Grossmutter/Krokodil...",
  "Big Brother und Kandidat",
  "Kandidat und Quizshowmaster",
  "Pilot und Crew/Passagiere/Stewardess...",
  "Chef und Mitarbeiter/Sekretärin",
  "Präsident und Kabinett (insb. in Kriegszeiten)",
  "Politiker und Wähler",
  "Buchhalter und Geschäftsmann/Frau",
  "Vorarbeiter und Arbeitskolonne",
  "Fabrikarbeiter und Konzernchef",
  "Herr und Diener/Dienstmädchen",
  "Dekorateur/Feng-Shui-Berater und Wohnungseigentümer",
  "Boxtrainer und Boxer (auch für andere Sportarten)",
  "Räuber/Mörder und sein bester Freund",
  "Waffenhändler und Pazifist",
  "Croupier und Roulettespieler",
  "Arzt und Patient/Krankenschwester",
  "Psychiater und Patient",
  "Tierarzt und Patient/Besitzer des Tiers",
  "Wärter und Psychisch Kranker",
  "Assistenzarzt und Chefarzt",
  "Schönheitschirurg und alterndes Topmodel",
  "Papst und Kardinal",
  "Priester und Gemeindemitglied",
  "Priester und Messdiener",
  "Guru und Jünger",
  "Kellner und Gast",
  "Verkäufer und Kunde",
  "Taxifahrer und Kunde",
  "Massschneider und Kunde",
  "Friseur und Kunde",
  "Automechaniker und Autobesitzer",
  "Bus/U-Bahn-Fahrer und Fahrgast",
  "Totengräber unter sich ...",
  "Mitarbeiter der Einwanderungsbehörde und Einwanderer ...",
  "McDonalds-Manager und 'Ökokrieger'",
  "Herr und Sklave",
  "Freunde aus der Kindheit, die sich wiedersehen"
];

function documentReady(fn: () => void) {
  if (
    document.readyState === "complete" ||
    document.readyState === "interactive"
  ) {
    setTimeout(fn, 1);
  } else {
    document.addEventListener("DOMContentLoaded", fn);
  }
}

function random(min: number, max: number) {
  return Math.random() * (max - min) + min;
}

function randomInt(min: number, max: number) {
  return Math.floor(Math.random() * (max - min + 1) + min);
}

declare var Howl: any;

function noise(selector: string, file: string) {
  let container = document.querySelector(selector);
  if (!container) return;
  const sound = new Howl({
    src: ["https://media.zottelig.ch/clown/audio/" + file],
    preload: false,
    html5: true
  });
  container.addEventListener("click", function() {
    sound.play();
  });
}
function noises(selector: string, files: any[]) {
  let container = document.querySelector(selector);
  if (!container) return;

  for (const file of files) {
    const sound = new Howl({
      src: ["https://media.zottelig.ch/clown/audio/" + file.name],
      preload: false,
      html5: true,
      volume: file.volume,
      loop: !file.random,
      stereo: typeof file.pan === "number" ? file.pan : undefined,
      onend: function() {
        if (file.random) {
          setTimeout(function() {
            if (!running) return;

            if (file.pan === "random") file.sound.stereo(random(-1, 1));
            file.sound.play();
          }, file.random * 1000);
        }
      }
    });

    file.sound = sound;
  }

  let running = false;
  container.addEventListener("click", function() {
    try {
      if (running) {
        running = false;

        for (const file of files) {
          file.sound.stop();
        }
      } else {
        running = true;

        for (const file of files) {
          if (!file.random) file.sound.play();
          else {
            setTimeout(function() {
              if (!running) return;

              if (file.pan === "random") file.sound.stereo(random(-1, 1));
              file.sound.play();
            }, file.random * 1000);
          }
        }
      }
    } catch (e) {
      alert(e);
    }
  });
}
function inspiration(selector: string, list: string | any[]) {
  let container = document.querySelector(selector);
  if (!container) return;
  container.addEventListener("click", function() {
    if (!container) return;
    const text = container.querySelector(".text");
    if (!text) return;
    text.textContent = list[randomInt(0, list.length - 1)];
  });
}

documentReady(function() {
  noise(".clown", "nose.mp3");

  noise(".service-bell", "service-bell.mp3");
  noises(".city", city);
  noises(".forest", forest);

  inspiration(".beruf", beruf);
  inspiration(".hobby", hobby);
  inspiration(".tick", tick);
  inspiration(".gefuehl", gefuehl);
  inspiration(".gefuehl-angenehm", gefuehlAngenehm);
  inspiration(".koerperteil", koerperteil);
  inspiration(".tier", tier);
  inspiration(".fabelwesen", fabelwesen);
  inspiration(".phobie", phobie);
  inspiration(".ort", ort);
  inspiration(".gebaeude", gebaeude);
  inspiration(".land", land);
  inspiration(".raum", raum);
  inspiration(".fortbewegungsmittel", fortbewegungsmittel);
  inspiration(".routine", routine);
  inspiration(".genre-fernseh", genreFernseh);
  inspiration(".genre-musik", genreMusik);
  inspiration(".beziehung", beziehung);
});

let city = [
  { name: "city/car-drive-by.mp3", volume: 1.0, pan: -0.6, random: 5 },
  { name: "city/car-horn-2.mp3", volume: 1.0, pan: -0.3, random: 600 },
  {
    name: "city/footsteps-on-concrete.mp3",
    volume: 0.9,
    pan: -0.1,
    random: 120
  },
  { name: "city/newspaper.mp3", volume: 0.6, pan: 0.2, random: 120 },
  { name: "city/quiet-bar.mp3", volume: 0.4, pan: 0.3 },
  {
    name: "city/residential-traffic.mp3",
    volume: 0.7,
    pan: -0.1,
    crossfade: 3.0
  },
  { name: "city/vespa-passing.mp3", volume: 0.9, pan: -0.2, random: 300 }
];

let forest = [
  {
    name: "forest/crow-three-times.mp3",
    volume: 0.8,
    pan: "random",
    random: 900
  },
  { name: "forest/cuckoo.mp3", volume: 0.8, pan: "random", random: 900 },
  { name: "forest/distant-forest-ambience.mp3", volume: 0.7 },
  {
    name: "forest/gray-woodpecker.mp3",
    volume: 0.8,
    pan: "random",
    random: 1800
  },
  {
    name: "forest/leaves-rustling.mp3",
    volume: 0.5,
    pan: 0.3,
    random: 150
  },
  {
    name: "forest/nightengale-call.mp3",
    volume: 0.8,
    pan: "random",
    random: 300
  },
  {
    name: "forest/nightengale-song1.mp3",
    volume: 0.8,
    pan: "random",
    random: 450
  },
  {
    name: "forest/white-throated-sparrow.mp3",
    volume: 0.8,
    pan: "random",
    random: 1800
  },
  {
    name: "forest/wind-blow-in-the-trees.mp3",
    volume: 0.5,
    pan: -0.2,
    random: 75
  },
  {
    name: "forest/wind-blows-in-leaves.mp3",
    volume: 0.5,
    pan: 0.5,
    random: 60
  },
  {
    name: "forest/woodpecker-adult.mp3",
    volume: 0.8,
    pan: "random",
    random: 1800
  },
  {
    name: "forest/woodpecker-young.mp3",
    volume: 0.8,
    pan: "random",
    random: 450
  }
];
